//
//  SmartCard.swift
//  PGPro
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

import Foundation

/**
 * Data structures modeling the (OpenPGP Smart Card specifications)[https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.4.pdf]
 */
struct SmartCard {

    struct Class {
        private init() {}

        static var singleWithoutSM: UInt8   = 0x00
        static var singleWithSM: UInt8      = 0x0C
        static var chainedWithoutSM: UInt8  = 0x10
        static var chainedWithSM: UInt8     = 0x1C
    }

    struct Ins {
        private init() {}

        static var select: UInt8            = 0xA4
        static var getData: UInt8           = 0xCA
        static var verify: UInt8            = 0x20
        static var changeRefData: UInt8     = 0x24
        static var resetRetryCounter: UInt8 = 0x2C
        // TODO: Whis one is it? DA or DB? Specifications unclear to me...
        //static var putData: UInt8           = 0xDA 0xDB
        static var generateAsymPair: UInt8  = 0x47
        static var computeDigSig: UInt8     = 0x2A
        static var decipher: UInt8          = 0x2A
        static var internalAuth: UInt8      = 0x88
        static var getResponse: UInt8       = 0xC0
        static var getChallenge: UInt8      = 0x84
        static var terminateDF: UInt8       = 0x44
        static var activateFile: UInt8      = 0xE6
    }

    /// Terminal-accessible, get-able OpenPGP smart card Data Object tags
    struct DataObjects {
        private init() {}

        struct Simple {
            private init() {}
            static var applicationIdentifier: UInt8     = 0x4F
            static var loginData: UInt8                 = 0x5E
            static var publicKeyURL: UInt16             = 0x5F50
            static var historicalBytes: UInt16          = 0x5F52
            static var pwStatus: UInt8                  = 0xC4
            static var keyInfo: UInt8                   = 0xDE
        }

        struct Constructed {
            private init() {}
            static var cardholderData: UInt8            = 0x65
            static var applicationData: UInt8           = 0x6E
            static var securitySupportTemplate: UInt8   = 0x7A
        }
    }

    /// Doesn't seem to be a very modern standard
    enum ISO5218Sex {
        case notKnown
        case male
        case female
        case notApplicable

        var description: String {
            switch self {
            case .notKnown: return "Not Known"
            case .male: return "Male"
            case .female: return "Female"
            case .notApplicable: return "Not Applicable"
            }
        }
    }

    struct Cardholder {
        var name: String?
        var language: String?
        var sex: ISO5218Sex?
    }

    enum KeyStatus {
        case keyNotPresent
        case keyGenerated
        case keyImported

        var description: String {
            switch self {
            case .keyNotPresent: return "Key not present"
            case .keyGenerated: return "Key generated by the card"
            case .keyImported: return "Key imported into the card"
            }
        }
    }

    struct KeyInformation {
        struct Signature {
            var status: KeyStatus?
            var reference: UInt8?
        }

        struct Decryption {
            var status: KeyStatus?
            var reference: UInt8?
        }

        struct Authentication {
            var status: KeyStatus?
            var reference: UInt8?
        }
    }

}
