# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do
  
  lane :screenshots do
    capture_screenshots()
  end

  lane :tests do
    run_tests(scheme: "PGPro")
  end
  
  lane :beta do
    asc_key_content = ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    asc_issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    asc_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]

    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )
    get_certificates
    get_provisioning_profile
    capture_screenshots()
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "PGPro")
    upload_to_testflight
  end 
  
  lane :release do
    asc_key_content = ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    asc_issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    asc_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]

    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )
    capture_screenshots()
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "PGPro")
    upload_to_app_store
  end 
end
