# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do
  
  lane :screenshots do
    capture_screenshots(scheme: "FLSnapshotScheme")
  end
  
  lane :beta do
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "PGPro")
    upload_to_testflight
  end 
  
  lane :release do
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "PGPro")
    upload_to_app_store
  end 
end
