# A list of devices you want to take the screenshots from
devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone 11",
   "iPhone 11 Pro",
   "iPhone 11 Pro Max"
])

languages([
   "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("FLSnapshotScheme")

output_directory("./fastlane/screenshots")

reinstall_app(true)
app_identifier("app.pgpro")
dark_mode(true)
clear_previous_screenshots(true)
